name: Daily Auto Contributions

on:
  schedule:
    - cron: "0 1 * * *"
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  contribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Update at $(date)" >> activity.log

      - name: Commit changes
        run: |
          git config --global user.name "Rayyankhaan"
          git config --global user.email "143524922+Rayyankhaan@users.noreply.github.com"
          git add activity.log
          git commit -m "Automated daily contribution" || echo "No changes"

      - name: Push
        run: git push
